language: python
python:
  - "2.7"
env:
 - PYTHONPATH='.'
before_install:
    sudo apt-get install -y libevent-dev python-gevent
    pip install -r requirements.txt --use-mirrors
script:
    python bin/run-test.py 